name: Docker Image CI

on: [push]

jobs:

  build:
 
    runs-on: ubuntu-latest
 
    steps:
    - uses: actions/checkout@v1
    - name: Build the Docker image（docker-kubectl）
      run: docker build . --file docker-kubectl/Dockerfile --tag docker.pkg.github.com/lqshow/dockerfiles/docker-kubectl:$(date +%s)
