name: Docker Image CI

on: [push]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@master
      with:
        submodules: true
    - name: CI Docker Login
      run: |
        docker login docker.pkg.github.com -u ${{ secrets.USERNAME }} -p ${{ secrets.PASSWORD }}

    - name: Build the Docker image（busybox-curl）
      run: |
        docker build . --file busybox-curl/Dockerfile --tag docker.pkg.github.com/lqshow/dockerfiles/busybox-curl:1.28
        docker push docker.pkg.github.com/lqshow/dockerfiles/busybox-curl:1.28

    - name: Build the Docker image（docker-kubectl）
      run: |
        docker build . --file docker-kubectl/Dockerfile --tag docker.pkg.github.com/lqshow/dockerfiles/docker-kubectl:latest
        docker push docker.pkg.github.com/lqshow/dockerfiles/docker-kubectl:latest

    # - name: Build the Docker image（igv-webapp）
    #   run: |
    #     ls -lha igv-webapp/resource/igv-webapp
    #     cd igv-webapp
    #     docker build . --file Dockerfile --tag docker.pkg.github.com/lqshow/dockerfiles/igv-webapp:0.0.1
    #     docker push docker.pkg.github.com/lqshow/dockerfiles/igv-webapp:0.0.1

    - name: Build the Docker image（helm-kubectl）
      run: |
        docker build . --file helm-kubectl/Dockerfile --tag docker.pkg.github.com/lqshow/dockerfiles/helm-kubectl:3.3.4
        docker push docker.pkg.github.com/lqshow/dockerfiles/helm-kubectl:3.3.4

    - name: Build the Docker image（kubetools）
      run: |
        cd kubetools && docker build -t docker.pkg.github.com/lqshow/dockerfiles/kubetools:0.0.1 .
        docker push docker.pkg.github.com/lqshow/dockerfiles/kubetools:0.0.1
